import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "./AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog With Next",
  description: "Generated by Blog With Next",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`max-w-7xl mx-auto px-4 md:px-6 lg:px-8${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header>
            <Navbar></Navbar>
          </header>
          <main>{children}</main>
        </body>
      </html>
    </AuthProvider>
  );
}
